name: CI Pipelines

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Clean Install
      run: mvn clean install
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn test
    - name: Package Artifact
      run: mvn package
    - name: Copy .Jar Artifact to staging Dir
      run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
      
      
